/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/search/base/button.vue')['default']
    Comment: typeof import('./src/components/comments/comment.vue')['default']
    Comments: typeof import('./src/components/comments/index.vue')['default']
    Confirm: typeof import('./src/components/search/base/confirm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImg: typeof import('element-plus/es')['ElImg']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Icon: typeof import('./src/components/search/base/icon.vue')['default']
    Icon2: typeof import('./src/components/search/base/icon2.vue')['default']
    MiniPlayer: typeof import('./src/components/miniPlayer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesHistory: typeof import('./src/components/routes-history.vue')['default']
    Search: typeof import('./src/components/search/index.vue')['default']
    SongTab: typeof import('./src/components/songTab/index.vue')['default']
    SongTable: typeof import('./src/components/songTable/index.vue')['default']
    Theme: typeof import('./src/components/theme/theme.vue')['default']
    Toggle: typeof import('./src/components/Toggle/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
